{% set name = "lckr_jupyterlab_variableinspector" %}
{% set version = "3.0.7" %}

package:
  name: jupyterlab-variableinspector
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 681432eb99bc9e3fb540dc40f98aa2e5558b500baa6695b054356f3149b549b2

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --install-option="--skip-npm" -vv

requirements:
  host:
    - python >=3.6
    - pip
    - jupyterlab >=3.0.0
    - jupyter-packaging >=0.7.9,<0.8.0
  run:
    - python >=3.6
    - jupyterlab >=3.0.0

test:
  commands:
    - jupyter labextension list 2>&1 | grep -ie "@lckr/jupyterlab_variableinspector.*OK.*(python, lckr_jupyterlab_variableinspector)"

about:
  home: https://github.com/lckr/jupyterlab-variableInspector
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Variable Inspector extension for Jupyterlab.

extra:
  recipe-maintainers:
    - fcollonval
