{% set name = "lckr_jupyterlab_variableinspector" %}
{% set version = "3.1.0" %}

package:
  name: jupyterlab-variableinspector
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0733fff6b78658cc4237076d105c9d19499a204deb1b800ffa65c23d236e722a

build:
  skip: true # [py<38 or s390x]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - hatch-jupyter-builder >=0.5
    - hatch-nodejs-version >=0.3.2
    - hatchling >=1.5.0
    - pip
    - python
  run:
    - python
    - jupyterlab >=3,<5

test:
  imports:
    - lckr_jupyterlab_variableinspector
  requires:
    - jupyterlab =4
    - pip
    - m2-grep # [win]
  commands:
    - pip check
    - jupyter labextension list
    - jupyter labextension list 2>&1 | grep -ie "@lckr/jupyterlab_variableinspector.*OK.*(python, lckr_jupyterlab_variableinspector)"

about:
  home: https://github.com/jupyterlab-contrib/jupyterlab-variableInspector
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Variable Inspector extension for Jupyterlab.
  dev_url: https://github.com/jupyterlab-contrib/jupyterlab-variableInspector
  doc_url: https://github.com/jupyterlab-contrib/jupyterlab-variableInspector

extra:
  recipe-maintainers:
    - fcollonval
